#!/bin/bash

grep '^\w' ~/.config/sxhkd/sxhkdrc \
    | tr '[[:lower:]]' '[[:upper:]]' \
    | sed \
        -e s/CONTROL/CAPSLOCK/ \
        -e s/ALT/LEFTMETA/ \
        -e s/SUPER/LEFTALT/ \
        -e s/SHIFT/LEFTSHIFT/ \
        -e s/RETURN/ENTER/ \
        -e s/DELETE/LEFTALT+RIGHTBRACE/ \
        -e s/INSERT/LEFTALT+Y/ \
        -e 's/ //g'

